# name: gen-plantuml

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - v*
#   pull_request:
#     branches:
#       - main

# permissions:
#   contents: write

# jobs:
#   generate_plantuml:
#     runs-on: ubuntu-latest
#     name: plantuml
#     steps:
#       - name: checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0
#       - name: plantuml
#         id: plantuml
#         uses: grassedge/generate-plantuml-action@v1.5
#         with:
#           path: "assets/uml"
#           message: "[skip] auto generate plant uml svgs"
#         env:
#           GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

